version: '3.8'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Bind mounts (two way sync)
      # One for backend and the other for frontend
      - ./server/src:/usr/src/app/src/
      - ./server/build:/usr/src/app/build/
    depends_on:
      - mongodb

  mongodb:
      image: mongo:latest
      restart: always
      ports:
        - "27018:27017"
      volumes:
        - mongodb_nfluencr:/data/db

volumes:
  mongodb_nfluencr:
