version: '3.8'
services:
  node-app:
    build: .
    ports:
      - "8080:3000"
    volumes:
      - .:/usr/src/app
      # node_modules workaround for volumes
      # https://stackoverflow.com/a/32785014
      - /usr/src/app/node_modules
